---
# tasks file for selinux
- name: Install libselinux-python package
  yum:
    name: libselinux-python
    state: present
  sudo: yes

- name: Configure SELinux
  selinux:
    state: "{{ selinux_state }}"
    policy: "{{ selinux_policy }}"
  sudo: yes
  notify:
  - reboot
  - wait
  - pause

- name: flush handlers
  meta: flush_handlers
