---
# handlers file for selinux
- name: reboot
  shell: sleep 2 && /sbin/shutdown -r now {{ selinux_reboot_message }}
  sudo: yes
  async: 1
  poll: 0
  ignore_errors: true
  when: selinux_reboot

- name: wait
  local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} delay={{ selinux_reboot_wait_delay }}
  when: selinux_reboot

- name: pause
  local_action: pause seconds=10
  when: selinux_reboot
